services:
  keycloak:
    build: .
    container_name: keycloak
    env_file:
      - keycloak.dev.env
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres
    env_file:
      - db.dev.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
